name: emv_services
description: WIZZIT payment services API
version: 0.0.1
homepage: https://wizzitdigital.com

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  intl: ^0.18.1
  nfc_manager: 2.0.3
  build_runner: ^2.3.3
  json_annotation: ^4.8.1
  json_serializable: ^6.6.2
  platform_device_id: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

