name: emv_services
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  intl: ^0.18.0   # breaking change
  build_runner: ^2.4.5
  json_annotation: ^4.8.1
  json_serializable: ^6.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter:

